### ISSUE TITLE
Metrics for graph comparison (Similarity Measures)

### ISSUE THREAD

**Issue by DusanStevic** [DusanStevic/SOTS#65]
1. [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance#:~:text=Informally%2C%20the%20Levenshtein%20distance%20between,considered%20this%20distance%20in%201965.) metric for string comparison:
"The Levenshtein distance between two strings is defined as the minimum number of edits needed to transform one string into the other, with the allowable edit operations being insertion, deletion, or substitution of a single character." - Wikipedia.com
"In information theory, linguistics and computer science, the Levenshtein distance is a string metric for measuring the difference between two sequences. Informally, the Levenshtein distance between two words is the minimum number of single-character edits (insertions, deletions or substitutions) required to change one word into the other. It is named after the Soviet mathematician Vladimir Levenshtein, who considered this distance in 1965.
Levenshtein distance may also be referred to as edit distance, although that term may also denote a larger family of distance metrics known collectively as edit distance."- Wikipedia.com
2. [Graph Edit Distance (GED)](https://networkx.org/documentation/stable/reference/algorithms/similarity.html) metric for graph comparison:
"The graph edit distance is the number of edge/node changes needed to make two graphs isomorphic."-[NetworkX — NetworkX documentation](https://networkx.org/documentation/stable/index.html#)

3. [https://networkx.org/documentation/stable/tutorial.html](https://networkx.org/documentation/stable/tutorial.html)

**Comment by DusanStevic** [comment]
"The Levenshtein distance between two strings is defined as the minimum number of edits needed to transform one string into the other, with the allowable edit operations being insertion, deletion, or substitution of a single character." - Wikipedia.com

**Comment by DusanStevic** [comment]
"The graph edit distance is the number of edge/node changes needed to make two graphs isomorphic."-NetworkX — NetworkX documentation

**Comment by MilicaVojnovic** [comment]
![example](https://user-images.githubusercontent.com/41190497/106463648-fb118200-6497-11eb-885a-078a09c3cdae.png)
general functionality
